import { combineReducers } from 'redux';
import {
    REDUX_LOGIN_HANDLER,
    REDUX_PRODUCT_LIST,
    REDUX_PRODUCT_UPDATE,
    REDUX_ADD_PRODUCT,
    REDUX_SEARCH_PRODUCT,
    REDUX_ADD_BRAND,
    REDUX_ADD_CATEGORY,
    REDUX_ADD_SUB_CATEGORY
} from './Reducer';
export default combineReducers({
    REDUX_LOGIN_HANDLER,
    REDUX_PRODUCT_LIST,
    REDUX_PRODUCT_UPDATE,
    REDUX_ADD_PRODUCT,
    REDUX_SEARCH_PRODUCT,
    REDUX_ADD_BRAND,
    REDUX_ADD_CATEGORY,
    REDUX_ADD_SUB_CATEGORY
});   